apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  labels:
    app: aop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  strategy:
    type: RollingUpdate			
    rollingUpdate:						
      maxSurge: 1							
      maxUnavailable: 0				
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: auth-app
          image: 11.2.2.50:2001/aop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32464
  selector:
    app: auth-app
